baseURL = "http://ecostudy.pro/"
languageCode = "ru-ru"
title = "Private clouds, microservices, DevOps"
theme = "hugo-apps-theme"

[params]
  avatar = "http://localhost:1313/img/cloud.jpg"
  author = "Облачная инфраструктура"
  info = "для разработчиков и тестировщиков"

[[menu.main]]
  name = "Тренинги"
  weight = 1
  url = "/trainings"

[[menu.main]]
  name = "Тренеры"
  weight = 2
  url = "/trainers"
