baseURL = "https://www.ecostudy.pro/"
languageCode = "ru-ru"
title = "Обучение облачной инфраструктуре"
theme = "hugo-apps-theme"

[params]
  googleAutoAds = ""
  avatar = "https://openclipart.org/download/103855/tux.svg"
  author = "Your name"
  info = "Any info about you"

[[menu.main]]
  name = "*Trainings*"
  weight = 3
  url = "/trainings"

[[menu.main]]
  name = "Website"
  weight = 2
  url = "https://gonapps.com"

[[menu.main]]
  name = "*Apps*"
  weight = 3
  url = "/apps"

[[menu.main]]
  name = "README"
  weight = 3
  url = "/README"


[[params.social]]
  name = "Github"
  weight = 1
  url = "https://github.com/gonapps"

[[params.social]]
  name = "Gitlab"
  weight = 2
  url = "https://gitlab.com/gonapps"

[[params.social]]
  name = "Website"
  weight = 3
  url = "https://gonapps.com"
